# -*- coding: utf-8 -*-
"""KM

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P1DdHXeS2Re1kWLBwyOk-_ddTqCcgbWQ
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.cluster import KMeans

"""Data Collection and Analysis"""

customer_data = pd.read_csv('/content/Mall_Customers.csv')

customer_data.head()

customer_data.shape

customer_data.info()

customer_data.describe()

customer_data.isnull().sum()

X = customer_data.iloc[:,[3,4]].values

print(X)

"""Finding with clusters sum of squares(wcss) value of different number of clusters"""

wcss = []

for i in range(1,11):
  kmeans = KMeans(n_clusters=i,init='k-means++',random_state=42)
  kmeans.fit(X)
  wcss.append(kmeans.inertia_)

"""Plot an Elbow"""

sns.set()
plt.plot(range(1,11),wcss)
plt.title('The Elbow point graph')
plt.xlabel('Number of clusters')
plt.ylabel('Wcss')
plt.show()

"""Optimum number of clusters = 5

"""

kmeans = KMeans(n_clusters=5, init="k-means++",random_state=0)

Y =kmeans.fit_predict(X)

print(Y)

"""Visualizing all the clusters"""

plt.figure(figsize=(8,8))
plt.scatter(X[Y==0,0],X[Y==0,1],s=50,c='green',label='Cluster 1')
plt.scatter(X[Y==1,0],X[Y==1,1],s=50,c='red',label='Cluster 2')
plt.scatter(X[Y==2,0],X[Y==2,1],s=50,c='yellow',label='Cluster 3')
plt.scatter(X[Y==3,0],X[Y==3,1],s=50,c='violet',label='Cluster 4')
plt.scatter(X[Y==4,0],X[Y==4,1],s=50,c='blue',label='Cluster 5')

# Plot the centroids
plt.scatter(kmeans.cluster_centers_[:,0],kmeans.cluster_centers_[:,1],s=100,c='cyan',label='centroids')

plt.title('Customer Groups')
plt.xlabel('Annual Income')
plt.ylabel('Spending Score')
plt.show()

